### PR TITLE
Initial sklearnex support

### PR DESCRIPTION
**Pull request by ethanglaser**
[please review the [Contribution Guidelines](http://epistasislab.github.io/tpot/contributing/) prior to submitting your pull request. go ahead and delete this line if you've already reviewed said guidelines.]

## What does this PR do?

Adds configs for and enables use of the Intel(R) Extension for Scikit-learn in tpot2.

## How should this PR be tested?

Ensure backwards compatibility - make sure previous configurations run without issue.
Test usage of the config files both using TPOTEstimator and TPOTRegressor/TPOTClassifier with root_config_dict set to classifiers_sklearnex or regressors_sklearnex respectively.

## Any background context you want to provide?

https://github.com/intel/scikit-learn-intelex/
Notebook with demonstration of speedup capabilities in tpot: https://colab.research.google.com/drive/1yeqbKg2Sv8affoHrOCsluunscjQnmqy5#scrollTo=h_TKDu-FnAFZ&line=5&uniqifier=1

## What are the relevant issues?

[#1316](https://github.com/EpistasisLab/tpot/issues/1316)

## Questions:

- Should a requirements-optional.txt be created?
- I would like to add an example, I see notebooks are primarily being used here which would be nice to demonstrate opportunities for speedups - any reservations about this?

### CODE REVIEW

**Comment by perib** [comment]
Thanks for the contribution! I did a quick test on my machine, and it works correctly. 

Some thoughts:

1. I think we can remove the `use_sklearnex` parameter. Instead, users can `use root_config_dict='classifiers_sklearnex',` which is already correctly working. (I'm considering removing the "Auto" as an option for root_config_dict for consistency with the other methods and instead explicitly setting it to classifiers/regressors in the TPOTClassifier/TPOTRegressor. ) This param might be confusing because the actual set of classifiers/regressors differs in the two configuration dictionaries. 


2. I also noticed that xgboost was included even though it is not part of sklearnex. Perhaps this works for now, but when #60 is addressed, perhaps we should separate it from the group. Users could then include it manually if they want.

**Comment by perib** [comment]
params_ElasticNet throws an error because log=True requires the search space to be >0. 

The solution could be to either:

`'alpha': 1 - trial.suggest_float(f'alpha_{name}', 0.0, 1.0),`

or 

`'alpha': 1 - trial.suggest_float(f'alpha_{name}', 1e-4, 1.0, log=True),`

**Comment by perib** [comment]
Realized I could simply make the commit. I think this is functional now and should be ready to merge

**Comment by ethanglaser** [comment]
Thanks for the review and merge @perib @nickotto - a couple other things we were thinking:
1. Addition of an example with use of sklearnex config - could be used to demonstrate potential for speedups over stock scikit-learn library (something along the lines of this notebook: https://colab.research.google.com/drive/1yeqbKg2Sv8affoHrOCsluunscjQnmqy5?usp=sharing)
2. Update to readme/docs mentioning option for sklearnex config usage
3. Some sort of optional requirements listing sklearnex as optional dependency

Please let me know if any of these additions would be of interest.

**Pull request merged**
